# =============================================================================
# DEV PROFILE - Development Environment
# =============================================================================
# Activate with: --spring.profiles.active=dev
# Or set environment variable: SPRING_PROFILES_ACTIVE=dev

# =============================================================================
# DEV PROFILE - Development Environment
# =============================================================================

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:orderdb_dev
    driver-class-name: org.h2.Driver
    username: sa
    password: dev123
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop  # Drop and recreate schema on startup
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    open-in-view: false
    defer-datasource-initialization: true  # KEY FIX: Wait for Hibernate to create schema first

  # Data initialization for dev profile
  sql:
    init:
      mode: always
      data-locations: classpath:data-dev.sql
      encoding: UTF-8
      continue-on-error: false

logging:
  level:
    root: INFO
    io.ganeshannt.asm.ops: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
